## Assuming the .travis.yml file is in the project directory, and there is a separate sub-directory for each service
## Use either `docker-compose` or individual `docker build` commands
## Build
script:
  - docker build -t udagram-api-feed ./udagram-api-feed
  - docker build -t udagram-api-user ./udagram-api-user
  - docker build -t udagram-frontend ./udagram-frontend
  - docker build -t udagram-reverseproxy ./udagram-reverseproxy
## Tagging
  - docker tag udagram-api-feed tran-cam-long/udagram-api-feed:v1
  - docker tag udagram-api-user tran-cam-long/udagram-api-user:v1
  - docker tag udagram-frontend tran-cam-long/udagram-frontend:v1
  - docker tag udagram-reverseproxy tran-cam-long/udagram-reverseproxy:v1

  ```bash
## Push

after_success:
## Assuming DOCKER_PASSWORD and DOCKER_USERNAME are set in the Travis repository settings
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push tran-cam-long/udagram-api-feed:v1
  - docker push tran-cam-long/udagram-api-user:v1
  - docker push tran-cam-long/udagram-frontend:v1
  - docker push tran-cam-long/udagram-reverseproxy:v1
